<<<<<<< HEAD
# Generated by Django 3.1.2 on 2020-10-18 19:44
=======
# Generated by Django 3.1.2 on 2020-10-19 03:14
>>>>>>> 69e2262960937793b3cf7ee0e134a77abde2ff5a

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_flag', models.BooleanField(default=False)),
                ('post_receive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comments.commentmodel')),
            ],
        ),
    ]
