# Generated by Django 3.1.2 on 2020-10-15 03:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instaprofilemodel',
            name='follower',
            field=models.ManyToManyField(blank=True, null=True, related_name='_instaprofilemodel_follower_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instaprofilemodel',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='_instaprofilemodel_following_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
