<<<<<<< HEAD:comments/migrations/0002_auto_20201018_0209.py
# Generated by Django 3.1.2 on 2020-10-18 02:09
=======
# Generated by Django 3.1.2 on 2020-10-18 01:46
>>>>>>> 2bcdf608b15eb876c10bc29b484c17e187dad0fc:comments/migrations/0002_auto_20201018_0146.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instapost', '0001_initial'),
<<<<<<< HEAD:comments/migrations/0002_auto_20201018_0209.py
        ('comments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
>>>>>>> 2bcdf608b15eb876c10bc29b484c17e187dad0fc:comments/migrations/0002_auto_20201018_0146.py
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='author_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='post_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='instapost.postmodel'),
        ),
    ]
