# Generated by Django 3.1.2 on 2020-10-17 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instapost', '0002_auto_20201016_2319'),
        ('comments', '0003_auto_20201017_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='post_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='instapost.postmodel'),
        ),
    ]
