# Generated by Django 3.1.2 on 2020-10-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('caption', models.TextField(blank=True, max_length=70, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/post_upload/', verbose_name='picture')),
                ('liked', models.BooleanField(default=False)),
            ],
        ),
    ]
