<<<<<<< HEAD
# Generated by Django 3.1.2 on 2020-10-13 01:36
=======
# Generated by Django 3.1.2 on 2020-10-14 00:49
>>>>>>> 0d0d19018a92d93e125a9ab197f54a63eb86d7a6

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD
                ('caption', models.TextField(blank=True, max_length=70, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/photo_upload/', verbose_name='picture')),
=======
                ('caption', models.CharField(blank=True, max_length=70, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/post_upload/', verbose_name='picture')),
>>>>>>> 0d0d19018a92d93e125a9ab197f54a63eb86d7a6
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
