# Generated by Django 3.1.2 on 2020-10-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
