<<<<<<< HEAD:instapost/migrations/0002_auto_20201018_0209.py
# Generated by Django 3.1.2 on 2020-10-18 02:09
=======
# Generated by Django 3.1.2 on 2020-10-18 01:46
>>>>>>> 2bcdf608b15eb876c10bc29b484c17e187dad0fc:instapost/migrations/0002_auto_20201018_0146.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instapost', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='like',
            field=models.ManyToManyField(related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
