# Generated by Django 3.1.2 on 2020-10-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='caption',
            field=models.TextField(blank=True, max_length=70, null=True),
        ),
    ]
