# Generated by Django 3.1.2 on 2020-10-06 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instapost', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='archive',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='likes',
        ),
    ]
