# Generated by Django 3.1.2 on 2020-10-06 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapost', '0002_auto_20201006_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/photo_upload/', verbose_name='picture'),
        ),
    ]
