# Generated by Django 3.1.2 on 2020-10-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapost', '0003_auto_20201006_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
