# Generated by Django 3.1.2 on 2020-10-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapost', '0004_auto_20201012_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/post_upload/', verbose_name='picture'),
        ),
    ]
