# Generated by Django 3.1.2 on 2020-10-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instapost', '0005_auto_20201013_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='caption',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
