# Generated by Django 3.1.2 on 2020-10-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instaprofilemodel',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
